dist: xenial
sudo: required
language: generic
cache: apt

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sudo apt-get update
  - sudo apt-get install ros-kinetic-desktop-full
  - source /opt/ros/kinetic/setup.bash
  - pip install catkin_pkg empy
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/
  - catkin_make
  - source devel/setup.bash

script:
  - cd ~/catkin_ws/src
  - git clone -b Indigo https://github.com/yzrobot/adaptive_clustering.git
  - cd ~/catkin_ws
  - catkin_make
